<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32546" started-at="2017-10-31T09:30:15Z" finished-at="2017-10-31T09:30:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32546" started-at="2017-10-31T09:30:15Z" finished-at="2017-10-31T09:30:48Z">
      <class name="Testcases.TC01_Login">
        <test-method status="PASS" signature="openBrowserAndGoToWebsite()[pri:0, instance:Testcases.TC01_Login@6d4b1c02]" name="openBrowserAndGoToWebsite" is-config="true" duration-ms="24599" started-at="2017-10-31T02:30:15Z" finished-at="2017-10-31T02:30:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowserAndGoToWebsite -->
        <test-method status="FAIL" signature="loginToAccount()[pri:0, instance:Testcases.TC01_Login@6d4b1c02]" name="loginToAccount" duration-ms="7931" started-at="2017-10-31T02:30:40Z" finished-at="2017-10-31T02:30:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Testcases.TC01_Login.loginToAccount(TC01_Login.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAccount -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Testcases.TC01_Login@6d4b1c02]" name="closeBrowser" is-config="true" duration-ms="0" started-at="2017-10-31T02:30:48Z" finished-at="2017-10-31T02:30:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Testcases.TC01_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
